import os
import sys
import json
import re
from openai import OpenAI
from github import Github, GithubException

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
REPO_NAME = os.environ["GITHUB_REPOSITORY"]
ISSUE_NUMBER = int(os.environ["ISSUE_NUMBER"])
EVENT_NAME = os.environ["EVENT_NAME"]
BOT_LOGIN = "github-actions[bot]"

gh = Github(GITHUB_TOKEN)
repo = gh.get_repo(REPO_NAME)
issue = repo.get_issue(ISSUE_NUMBER)

client = OpenAI(
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key=os.environ["GEMINI_API_KEY"]
)

SYSTEM_PROMPT = """You are a Java coding assistant for a Java 21 Maven project.

Your behavior depends on the conversation stage:

STAGE 1 — New issue, no previous bot comments:
- Read the issue carefully
- Propose a clear implementation plan:
  * Exact method signatures
  * Validation rules and edge cases
  * List of tests you will write
- End your response with exactly: "Shall I proceed? Reply **@ai go** to implement."

STAGE 2 — User gave feedback on the plan:
- Update the plan based on feedback
- Ask for confirmation again

STAGE 3 — User wrote "@ai go" (or "go ahead" / "implement" / "yes, proceed"):
- Respond ONLY with a raw JSON object, no markdown, no explanation:
{"action":"implement","files":[{"path":"src/main/java/lab/ClassName.java","content":"...full file content..."}]}

Always follow coding conventions from AGENT.md.
"""


def get_file(path):
    try:
        return repo.get_contents(path).decoded_content.decode("utf-8")
    except GithubException:
        return None


def get_java_sources():
    result = ""
    try:
        for f in repo.get_contents("src/main/java/lab"):
            if f.name.endswith(".java"):
                result += f"\n\n### {f.path}\n```java\n{f.decoded_content.decode()}\n```"
        for f in repo.get_contents("src/test/java/lab"):
            if f.name.endswith(".java"):
                result += f"\n\n### {f.path}\n```java\n{f.decoded_content.decode()}\n```"
    except GithubException:
        pass
    return result


def build_messages():
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]

    agent_md = get_file("AGENT.md")
    if agent_md:
        messages.append({"role": "user", "content": f"Project instructions (AGENT.md):\n{agent_md}"})
        messages.append({"role": "assistant", "content": "Understood, I will follow these instructions."})

    sources = get_java_sources()
    if sources:
        messages.append({"role": "user", "content": f"Current codebase:{sources}"})
        messages.append({"role": "assistant", "content": "I have reviewed the existing code."})

    messages.append({
        "role": "user",
        "content": f"**Issue #{issue.number}: {issue.title}**\n\n{issue.body or '(no description)'}"
    })

    for comment in issue.get_comments():
        role = "assistant" if comment.user.login == BOT_LOGIN else "user"
        messages.append({"role": role, "content": comment.body})

    return messages


def extract_json(text):
    """Extract JSON from response even if wrapped in markdown code block."""
    match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', text, re.DOTALL)
    if match:
        return match.group(1)
    if text.strip().startswith("{"):
        return text.strip()
    return None


def implement(data):
    branch = f"ai/issue-{issue.number}"
    default = repo.default_branch
    sha = repo.get_git_ref(f"heads/{default}").object.sha

    try:
        repo.create_git_ref(f"refs/heads/{branch}", sha)
    except GithubException:
        pass  # branch already exists, continue

    for f in data["files"]:
        try:
            existing = repo.get_contents(f["path"], ref=branch)
            repo.update_file(
                f["path"],
                f"ai: implement #{issue.number}",
                f["content"],
                existing.sha,
                branch=branch
            )
        except GithubException:
            repo.create_file(
                f["path"],
                f"ai: implement #{issue.number}",
                f["content"],
                branch=branch
            )

    pr = repo.create_pull(
        title=f"AI: {issue.title}",
        body=f"Closes #{issue.number}\n\nGenerated by AI agent.",
        head=branch,
        base=default
    )
    issue.create_comment(f"Done! PR opened: {pr.html_url}\n\nCI will run tests automatically.")


def main():
    messages = build_messages()

    response = client.chat.completions.create(
        model="gemini-1.5-flash",
        messages=messages,
        temperature=0.2,
        max_tokens=4000
    )

    reply = response.choices[0].message.content.strip()
    json_str = extract_json(reply)

    if json_str:
        try:
            data = json.loads(json_str)
            if data.get("action") == "implement":
                implement(data)
                return
        except json.JSONDecodeError:
            pass

    issue.create_comment(reply)


if __name__ == "__main__":
    main()
