import os
import json
import re
import google.generativeai as genai
from github import Github, Auth, GithubException

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
REPO_NAME = os.environ["GITHUB_REPOSITORY"]
ISSUE_NUMBER = int(os.environ["ISSUE_NUMBER"])
BOT_LOGIN = "github-actions[bot]"

gh = Github(auth=Auth.Token(GITHUB_TOKEN))
repo = gh.get_repo(REPO_NAME)
issue = repo.get_issue(ISSUE_NUMBER)

genai.configure(api_key=os.environ["GEMINI_API_KEY"])

SYSTEM_PROMPT = """You are a Java coding assistant for a Java 21 Maven project.

Your behavior depends on the conversation stage:

STAGE 1 — New issue, no previous bot comments:
- Read the issue carefully
- Propose a clear implementation plan:
  * Exact method signatures
  * Validation rules and edge cases
  * List of tests you will write
- End your response with exactly: "Shall I proceed? Reply **@ai go** to implement."

STAGE 2 — User gave feedback on the plan:
- Update the plan based on feedback
- Ask for confirmation again

STAGE 3 — User wrote "@ai go" (or "go ahead" / "implement" / "yes, proceed"):
- Respond ONLY with a raw JSON object, no markdown, no explanation:
{"action":"implement","files":[{"path":"src/main/java/lab/ClassName.java","content":"...full file content..."}]}

Always follow coding conventions from AGENT.md.
"""


def get_file(path):
    try:
        return repo.get_contents(path).decoded_content.decode("utf-8")
    except GithubException:
        return None


def get_java_sources():
    result = ""
    try:
        for f in repo.get_contents("src/main/java/lab"):
            if f.name.endswith(".java"):
                result += f"\n\n### {f.path}\n```java\n{f.decoded_content.decode()}\n```"
        for f in repo.get_contents("src/test/java/lab"):
            if f.name.endswith(".java"):
                result += f"\n\n### {f.path}\n```java\n{f.decoded_content.decode()}\n```"
    except GithubException:
        pass
    return result


def build_history():
    """Build conversation history in Gemini format."""
    history = []

    agent_md = get_file("AGENT.md")
    if agent_md:
        history.append({"role": "user", "parts": [f"Project instructions (AGENT.md):\n{agent_md}"]})
        history.append({"role": "model", "parts": ["Understood, I will follow these instructions."]})

    sources = get_java_sources()
    if sources:
        history.append({"role": "user", "parts": [f"Current codebase:{sources}"]})
        history.append({"role": "model", "parts": ["I have reviewed the existing code."]})

    history.append({
        "role": "user",
        "parts": [f"**Issue #{issue.number}: {issue.title}**\n\n{issue.body or '(no description)'}"]
    })

    for comment in issue.get_comments():
        role = "model" if comment.user.login == BOT_LOGIN else "user"
        history.append({"role": role, "parts": [comment.body]})

    return history


def extract_json(text):
    match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', text, re.DOTALL)
    if match:
        return match.group(1)
    if text.strip().startswith("{"):
        return text.strip()
    return None


def implement(data):
    branch = f"ai/issue-{issue.number}"
    default = repo.default_branch
    sha = repo.get_git_ref(f"heads/{default}").object.sha

    try:
        repo.create_git_ref(f"refs/heads/{branch}", sha)
    except GithubException:
        pass

    for f in data["files"]:
        try:
            existing = repo.get_contents(f["path"], ref=branch)
            repo.update_file(
                f["path"],
                f"ai: implement #{issue.number}",
                f["content"],
                existing.sha,
                branch=branch
            )
        except GithubException:
            repo.create_file(
                f["path"],
                f"ai: implement #{issue.number}",
                f["content"],
                branch=branch
            )

    pr = repo.create_pull(
        title=f"AI: {issue.title}",
        body=f"Closes #{issue.number}\n\nGenerated by AI agent.",
        head=branch,
        base=default
    )
    issue.create_comment(f"Done! PR opened: {pr.html_url}\n\nCI will run tests automatically.")


def main():
    history = build_history()

    # Last message is sent separately, history contains everything before it
    last = history.pop()

    model = genai.GenerativeModel(
        model_name="gemini-3.8-flash",
        system_instruction=SYSTEM_PROMPT
    )
    chat = model.start_chat(history=history)
    response = chat.send_message(last["parts"][0])

    reply = response.text.strip()
    json_str = extract_json(reply)

    if json_str:
        try:
            data = json.loads(json_str)
            if data.get("action") == "implement":
                implement(data)
                return
        except json.JSONDecodeError:
            pass

    issue.create_comment(reply)


if __name__ == "__main__":
    main()
